---
title: "TOC/Fe comb"
author: "Abby Lewis"
date: "9/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
toc = read.csv("../data/processed_data/TOC_formatted.csv")%>%
  select(-Day)
fe = read.csv("../data/processed_data/acidified_Fe_formatted.csv")%>%
  select(-Day)
do = read.csv("../data/processed_data/DO_formatted.csv")%>%
  select(-Sample)%>%
  mutate(Sample_day = Day)

full = toc%>%
  full_join(fe)%>%
  full_join(do)

full$Treatment[full$Treatment=="Anoxic to oxic"&full$Sample_day<=13]<-"Anoxic"
full$Treatment[full$Treatment=="Oxic to anoxic"&full$Sample_day<=13]<-"Oxic"

facets = c("DOC (mg/L)", " Total iron (mg/L)","DO (mg/L)")
names(facets) = c("NPOC","Iron","DO_mgL")

f = full%>%
  filter(filt == "Unfiltered")%>%
  mutate(Iron = Conc/1000)%>%
  pivot_longer(cols = c(NPOC,Iron,DO_mgL))%>%
  ggplot(aes(x = Sample_day, y = value, color = Treatment))+
  geom_point()+
  ylab("")+
  xlab("Day of experiment")+
  geom_vline(xintercept = 13.5)+
  scale_color_manual(values = c("#175676","#D58936","#A44200","#4BA3C3")) +
  facet_grid(name~Status, scale = "free_y", switch = "y", labeller = labeller(name = facets))+
  theme_bw()+
  theme(strip.text.x = element_blank(),
        legend.position = "top",
        text = element_text(size=18))+
  scale_y_continuous(position = "right")

jpeg("../figures/combined_exp_graph.jpg", width = 8, height = 6, units = "in",res = 300)
f
dev.off()

facets = c("DOC (mg/L)", "Soluble Fe (mg/L)","Total Fe (mg/L)","DO (mg/L)")
names(facets) = c("NPOC", "Filtered","Unfiltered","DO_mgL")

formatted = full%>%
  mutate(Iron = Conc/1000)%>%
  pivot_wider(names_from = filt,
              values_from = c(Iron))%>%
  pivot_longer(cols = c(NPOC, Unfiltered,Filtered,DO_mgL))%>%
  filter(!is.na(Status))

formatted$name <- factor(formatted$name, levels = c("DO_mgL", "NPOC", "Unfiltered", "Filtered"))

f = formatted%>%
  ggplot(aes(x = Sample_day, y = value, color = Treatment))+
  geom_point(size  =1)+
  ylab("")+
  xlab("Day of experiment")+
  geom_vline(xintercept = 13.5)+
  scale_color_manual(values = c("#175676","#D58936","#A44200","#4BA3C3")) +
  facet_grid(name~Status, scale = "free_y", switch = "y", labeller = labeller(name = facets))+
  theme_bw()+
  theme(strip.text.x = element_blank(),
        legend.position = "top")+
  scale_y_continuous(position = "right")

jpeg("../figures/combined_exp_graph_full.jpg", width = 6, height = 6, units = "in",res = 300)
f
dev.off()

destructive = formatted[!duplicated(formatted$Sample),]
destructive_df = data.frame(Treatment = c(""), days = c(NA), counts = c(NA))
for(Treat in c("Oxic","Anoxic","Anoxic to oxic","Oxic to anoxic")){
  new = destructive%>%
    filter(Treatment == Treat)
  days = 1:40
  counts = c()
  for(i in days){
    n = sum(new$Sample_day>i)
    counts = c(counts, n)
  }
  to_join = data.frame(Treatment = Treat,days,counts)
  destructive_df = destructive_df%>%
    full_join(to_join)
}

destructive_df%>%
  ggplot(aes(x = days, y = counts, color = Treatment))+
  geom_line()
```

