---
title: "Iron graphs"
author: "Abby Lewis"
date: "1/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
start = as.Date("2019-05-15")
end = as.Date("2019-09-15")
metals_f <- read_excel("Metals_2019_Formatted.xlsx", sheet = "FCR")
metals_b <- read_excel("Metals_2019_Formatted.xlsx", sheet = "BVR")

metals_fcr <- metals_f%>%
  filter(Date >= start,
         Date <= end)%>%
  select(Date, Depth_m, TFe_mgl, SFe_mgl)%>%
  mutate(Res = "FCR")

metals_bvr <- metals_b%>%
  filter(Date >= start,
         Date <= end)%>%
  select(Date, Depth, Tfe, Sfe)%>%
  mutate(Res = "BVR")



## I changed my mind and decided it would be easier (and more informative) to make heatmaps in matlab than to calculate volume weighted Fe for both reservoirs and plot that. 

#Formatting data for matlab

POSIXt2matlabUTC = function(x) {
  if (class(x)[1] == "POSIXct") {
    x = as.POSIXlt(x, tz = "UTC") #convert to UTC time zone
    days = as.numeric(x) / 86400 #convert to days
    datenum = days + 719529 #convert to MATLAB datenum
  } else if (class(x)[1] == "POSIXlt") {
    x = as.POSIXlt(x, tz = "UTC") #convert to UTC time zone
    days = as.numeric(x) / 86400  #convert to days
    datenum = days + 719529 #convert to MATLAB datenum
  } else {stop("POSIXct or POSIXlt object required for input")}
  return(datenum)
}

fcr_metals_matlab <- metals_fcr[-5]
#Convert dates into matlab format
fcr_metals_matlab$Date <- POSIXt2matlabUTC(fcr_metals_matlab$Date)

bvr_metals_matlab <- metals_bvr[-5]
#Convert dates into matlab format
bvr_metals_matlab$Date <- POSIXt2matlabUTC(bvr_metals_matlab$Date)

write_csv(fcr_metals_matlab, "fcr_metals_matlab.csv", col_names = FALSE)
write_csv(bvr_metals_matlab, "bvr_metals_matlab.csv", col_names = FALSE)

```

```{r}
metals_fcr

vol <- read_csv("FCR_vol.csv")
vol_bvr <- read_csv("BVR_Vol_ASL.csv")

fe_depths <- c(0.1, 1.6, 3.8, 5, 6.2, 8, 9)
lower = 0
upper = fe_depths[1]+(fe_depths[2]-fe_depths[1])/2
fe_vols = c(sum(vol$'Volume (L)'[vol$'Depth (m)' < upper & vol$'Depth (m)' > lower]))
fe_layer_depth <- c()
fe_layer_depth[1] <- upper-lower
for (d in 2:length(fe_depths)){
  lower = fe_depths[d]-(fe_depths[d]-fe_depths[d-1])/2
  upper = fe_depths[d]+(fe_depths[d+1]-fe_depths[d])/2
  if(d == length(fe_depths-1)){upper = 9.3}
  fe_vols = c(fe_vols, sum(vol$'Volume (L)'[vol$'Depth (m)' < upper & vol$'Depth (m)' > lower]))
  fe_layer_depth[d] <- upper-lower
}
vol2 = data.frame(fe_depths,fe_vols, fe_layer_depth)


fe_depths <- c(0.1,3,6,9,11)
lower = 0
upper = fe_depths[1]+(fe_depths[2]-fe_depths[1])/2
fe_vols = c(sum(vol_bvr$Volume_L[vol_bvr$Depth_m < upper & vol_bvr$Depth_m > lower], na.rm = TRUE))
fe_layer_depth <- c()
fe_layer_depth[1] <- upper-lower
for (d in 2:length(fe_depths)){
  lower = fe_depths[d]-(fe_depths[d]-fe_depths[d-1])/2
  upper = fe_depths[d]+(fe_depths[d+1]-fe_depths[d])/2
  if(d == length(fe_depths-1)){upper = 13}
  fe_vols = c(fe_vols, sum(vol_bvr$Volume_L[vol_bvr$Depth_m < upper & vol_bvr$Depth_m > lower], na.rm = TRUE))
  fe_layer_depth[d] <- upper-lower
}
vol2_bvr = data.frame(fe_depths,fe_vols, fe_layer_depth)

vw_fe_bvr <- metals_bvr%>%
  mutate(Depth_m = as.numeric(Depth)) %>%
  full_join(vol2_bvr, by = c("Depth_m"="fe_depths")) %>%
  mutate(TFe_mg = Tfe*fe_vols,
         SFe_mg = Sfe*fe_vols)%>%
  group_by(Date)%>%
  filter(Depth_m %in% c(6,9,11))%>%
  summarise(TFe_vw = sum(TFe_mg)/sum(fe_vols),
            SFe_vw = sum(SFe_mg)/sum(fe_vols),
            Res = "BVR")

vw_fe_fcr <- metals_fcr%>%
  mutate(Depth_m = as.numeric(Depth_m)) %>%
  full_join(vol2, by = c("Depth_m"="fe_depths")) %>%
  mutate(TFe_mg = TFe_mgl*fe_vols,
         SFe_mg = SFe_mgl*fe_vols)%>%
  group_by(Date)%>%
  filter(Depth_m %in% c(6.2,8,9))%>%
  summarise(TFe_vw = sum(TFe_mg)/sum(fe_vols),
            SFe_vw = sum(SFe_mg)/sum(fe_vols),
            Res = "FCR")

vw_fe_bvr%>%
  full_join(vw_fe_fcr)%>%
  ggplot(aes(x = Date, y = SFe_vw, color = Res))+
  geom_line()

t.test(vw_fe_bvr$TFe_vw,vw_fe_fcr$TFe_vw)

mean(vw_fe_fcr$TFe_vw)
sd(vw_fe_fcr$TFe_vw)
mean(vw_fe_bvr$TFe_vw, na.rm = T)
sd(vw_fe_bvr$TFe_vw, na.rm = T)

t.test(vw_fe_bvr$SFe_vw,vw_fe_fcr$SFe_vw)

mean(vw_fe_fcr$SFe_vw)
sd(vw_fe_fcr$SFe_vw)
mean(vw_fe_bvr$SFe_vw, na.rm = T)
sd(vw_fe_bvr$SFe_vw, na.rm = T)

```

